---
title: "paper1.rmd"
author: "Huakun Shen"
date: "05/02/2022"
output: pdf_document
---


```{r install and load packages, echo=FALSE}
# install.packages("opendatatoronto")
# install.packages("knitr")
# install.packages("janitor")
# install.packages("lubridate")
# install.packages("opendatatoronto")
# install.packages("tidyverse")
# install.packages("tidyr")
# install.packages("dplyr")
library(knitr)
library(janitor)
library(lubridate)
library(opendatatoronto)
library(tidyverse)
library(tidyr)
library(dplyr)
```

```{r get package, echo=FALSE}
package_id <- "fc4d95a6-591f-411f-af17-327e6c5d03c7"
package <- show_package(package_id)
package
# get all resources for this package
resources <- list_package_resources(package_id)
 
# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
 
# load the first datastore resource as a sample
data <- filter(datastore_resources, row_number()==1) %>% get_resource()
data
```

```{r}
colnames(data)
```





























